name: wikiviews-monthly
on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 5 1 * *"   # monthly on the 1st at 05:17 UTC
permissions:
  contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Fetch monthly pageviews and write CSV
        run: |
          python - <<'PY'
          import os, csv, json, urllib.request, urllib.parse
          from datetime import datetime, timezone

          # Config
          TITLE_RAW = "Amazon (company)"     # human-readable title
          PROJECT = "en.wikipedia"           # language.project
          OUTPATH = "data/wikiviews_amazon_company_monthly.csv"

          # 2019-01 to current month (inclusive)
          now = datetime.now(timezone.utc)
          start = datetime(2019, 1, 1, tzinfo=timezone.utc)
          end = datetime(now.year, now.month, 1 tzinfo=timezone.utc)

          def ts(d): return d.strftime("%Y%m0100")

          # Encode title and set a proper User-Agent per Wikimedia API policy
          title_enc = urllib.parse.quote(TITLE_RAW, safe='')
          url = (f"https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/"
                 f"{PROJECT}/all-access/user/{title_enc}/monthly/{ts(start)}/{ts(end)}")

          headers = {
            "User-Agent": "signal-spiral-bot/1.0 (https://github.com/chsmithiii/signal-spiral; contact: chsmithiii@gmail.com)"
          }
          req = urllib.request.Request(url, headers=headers)
          with urllib.request.urlopen(req) as r:
            data = json.load(r)

          items = data.get("items", [])
          rows = [("date","views")]
          for it in items:
            t = it["timestamp"]              # e.g., 2025010100
            y, m = int(t[:4]), int(t[4:6])
            rows.append((f"{y:04d}-{m:02d}-01", str(it["views"])))

          os.makedirs("data", exist_ok=True)
          with open(OUTPATH, "w", newline="", encoding="utf-8") as f:
            csv.writer(f).writerows(rows)

          print(f"Wrote {len(rows)-1} rows to {OUTPATH}")
          PY
      - name: Commit data if changed
        env:
          AUTHOR_NAME: "${{ github.actor }}"
          AUTHOR_EMAIL: "${{ github.actor }}@users.noreply.github.com"
        run: |
          set -e
          if git diff --quiet -- data/wikiviews_amazon_company_monthly.csv; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
          git add data/wikiviews_amazon_company_monthly.csv
          git commit -m "data(signal-spiral): update Wikimedia pageviews (Amazon company) monthly"
          git push
